name: Python application

on:
  push:
    branches:
      - main 


jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python 3.13.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.13.5  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black isort flake8  

    - name: Format code with black
      run: |
        black . --exclude=".env" 

    - name: Sort imports with isort
      run: |
        isort .

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
